name: Run Ansible Playbook

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Ansible Playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: patch-server.yml
        inventory: hosts.ini
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        options: |
          --user your_ssh_user
          --private-key /path/to/private/key
