- name: Update all packages on a server
  hosts: all
  become: yes

  tasks:
  - name: Update all packages to the latest version (Debian/Ubuntu)
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: Update all packages to the latest version (CentOS/RHEL)
    ansible.builtin.yum:
      name: '*'
      state: latest
    when: ansible_facts['os_family'] == "RedHat"
